//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestAuth
{
    using System;
    using System.Collections.Generic;
    
    public partial class analyzer_logs
    {
        public int id { get; set; }
        public int analyzer_id { get; set; }
        public int order_service_id { get; set; }
        public System.DateTime started_at { get; set; }
        public Nullable<System.DateTime> completed_at { get; set; }
        public Nullable<int> duration_seconds { get; set; }
    
        public virtual analyzers analyzers { get; set; }
        public virtual order_services order_services { get; set; }
    }
}
