//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestAuth
{
    using System;
    using System.Collections.Generic;
    
    public partial class analyzers
    {
        public analyzers()
        {
            this.analyzer_logs = new HashSet<analyzer_logs>();
            this.order_services = new HashSet<order_services>();
        }
    
        public int id { get; set; }
        public string analyzer_code { get; set; }
        public string analyzer_name { get; set; }
        public string model { get; set; }
        public string location { get; set; }
    
        public virtual ICollection<analyzer_logs> analyzer_logs { get; set; }
        public virtual ICollection<order_services> order_services { get; set; }
    }
}
