//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestAuth
{
    using System;
    using System.Collections.Generic;
    
    public partial class archive_log
    {
        public int id { get; set; }
        public string table_name { get; set; }
        public int record_id { get; set; }
        public Nullable<int> archived_by { get; set; }
        public string archive_reason { get; set; }
        public string original_data { get; set; }
        public Nullable<System.DateTime> archived_at { get; set; }
    
        public virtual employees employees { get; set; }
    }
}
