//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestAuth
{
    using System;
    using System.Collections.Generic;
    
    public partial class bloodservice
    {
        public int id { get; set; }
        public int blood_id { get; set; }
        public string service_code { get; set; }
        public string result { get; set; }
        public Nullable<bool> finished { get; set; }
        public Nullable<bool> accepted { get; set; }
        public string status { get; set; }
        public string analyzer { get; set; }
        public Nullable<int> user_id { get; set; }
    
        public virtual blood blood { get; set; }
        public virtual employees employees { get; set; }
    }
}
