//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestAuth
{
    using System;
    using System.Collections.Generic;
    
    public partial class blood
    {
        public blood()
        {
            this.bloodservice = new HashSet<bloodservice>();
        }
    
        public int id { get; set; }
        public int patient { get; set; }
        public string barcode { get; set; }
        public Nullable<System.DateTime> date { get; set; }
    
        public virtual patients patients { get; set; }
        public virtual ICollection<bloodservice> bloodservice { get; set; }
    }
}
