//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestAuth
{
    using System;
    using System.Collections.Generic;
    
    public partial class employee_roles
    {
        public employee_roles()
        {
            this.employees = new HashSet<employees>();
        }
    
        public int id { get; set; }
        public string role_name { get; set; }
        public string description { get; set; }
    
        public virtual ICollection<employees> employees { get; set; }
    }
}
