//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestAuth
{
    using System;
    using System.Collections.Generic;
    
    public partial class employee_services
    {
        public int employee_id { get; set; }
        public int service_id { get; set; }
        public Nullable<bool> is_primary { get; set; }
    
        public virtual employees employees { get; set; }
        public virtual services services { get; set; }
    }
}
