//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestAuth
{
    using System;
    using System.Collections.Generic;
    
    public partial class employees
    {
        public employees()
        {
            this.archive_log = new HashSet<archive_log>();
            this.bloodservice = new HashSet<bloodservice>();
            this.employee_services = new HashSet<employee_services>();
            this.invoices = new HashSet<invoices>();
            this.order_services = new HashSet<order_services>();
            this.order_services1 = new HashSet<order_services>();
        }
    
        public int id { get; set; }
        public string full_name { get; set; }
        public string login { get; set; }
        public string password_hash { get; set; }
        public int role_id { get; set; }
        public string phone { get; set; }
        public string email { get; set; }
        public string department { get; set; }
        public Nullable<System.DateTime> last_login { get; set; }
    
        public virtual ICollection<archive_log> archive_log { get; set; }
        public virtual ICollection<bloodservice> bloodservice { get; set; }
        public virtual employee_roles employee_roles { get; set; }
        public virtual ICollection<employee_services> employee_services { get; set; }
        public virtual ICollection<invoices> invoices { get; set; }
        public virtual ICollection<order_services> order_services { get; set; }
        public virtual ICollection<order_services> order_services1 { get; set; }
    }
}
