//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestAuth
{
    using System;
    using System.Collections.Generic;
    
    public partial class insurance_companies
    {
        public insurance_companies()
        {
            this.invoices = new HashSet<invoices>();
        }
    
        public int id { get; set; }
        public string company_name { get; set; }
        public string address { get; set; }
        public string inn { get; set; }
        public string checking_account { get; set; }
        public string bik { get; set; }
        public string phone { get; set; }
        public string email { get; set; }
    
        public virtual ICollection<invoices> invoices { get; set; }
    }
}
