//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestAuth
{
    using System;
    using System.Collections.Generic;
    
    public partial class invoices
    {
        public invoices()
        {
            this.orders = new HashSet<orders>();
        }
    
        public int id { get; set; }
        public string invoice_number { get; set; }
        public int insurance_company_id { get; set; }
        public System.DateTime invoice_date { get; set; }
        public decimal total_amount { get; set; }
        public Nullable<System.DateTime> due_date { get; set; }
        public Nullable<bool> is_paid { get; set; }
        public int created_by { get; set; }
    
        public virtual employees employees { get; set; }
        public virtual insurance_companies insurance_companies { get; set; }
        public virtual ICollection<orders> orders { get; set; }
    }
}
