//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestAuth
{
    using System;
    using System.Collections.Generic;
    
    public partial class order_services
    {
        public order_services()
        {
            this.analyzer_logs = new HashSet<analyzer_logs>();
        }
    
        public int id { get; set; }
        public int order_id { get; set; }
        public int service_id { get; set; }
        public int status_id { get; set; }
        public Nullable<int> assigned_to { get; set; }
        public Nullable<int> performed_by { get; set; }
        public Nullable<int> analyzer_id { get; set; }
        public string result { get; set; }
        public Nullable<decimal> actual_price { get; set; }
    
        public virtual ICollection<analyzer_logs> analyzer_logs { get; set; }
        public virtual analyzers analyzers { get; set; }
        public virtual employees employees { get; set; }
        public virtual employees employees1 { get; set; }
        public virtual orders orders { get; set; }
        public virtual services services { get; set; }
        public virtual service_statuses service_statuses { get; set; }
    }
}
