//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestAuth
{
    using System;
    using System.Collections.Generic;
    
    public partial class orders
    {
        public orders()
        {
            this.order_services = new HashSet<order_services>();
            this.invoices = new HashSet<invoices>();
        }
    
        public int id { get; set; }
        public string order_number { get; set; }
        public int patient_id { get; set; }
        public System.DateTime order_date { get; set; }
        public int status_id { get; set; }
        public Nullable<decimal> total_amount { get; set; }
        public Nullable<int> execution_days { get; set; }
    
        public virtual ICollection<order_services> order_services { get; set; }
        public virtual order_statuses order_statuses { get; set; }
        public virtual patients patients { get; set; }
        public virtual ICollection<invoices> invoices { get; set; }
    }
}
