//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestAuth
{
    using System;
    using System.Collections.Generic;
    
    public partial class order_statuses
    {
        public order_statuses()
        {
            this.orders = new HashSet<orders>();
        }
    
        public int id { get; set; }
        public string status_name { get; set; }
        public string description { get; set; }
    
        public virtual ICollection<orders> orders { get; set; }
    }
}
