//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestAuth
{
    using System;
    using System.Collections.Generic;
    
    public partial class services
    {
        public services()
        {
            this.employee_services = new HashSet<employee_services>();
            this.order_services = new HashSet<order_services>();
        }
    
        public int id { get; set; }
        public string service_code { get; set; }
        public string service_name { get; set; }
        public decimal price { get; set; }
        public int execution_days { get; set; }
        public Nullable<decimal> average_deviation { get; set; }
    
        public virtual ICollection<employee_services> employee_services { get; set; }
        public virtual ICollection<order_services> order_services { get; set; }
    }
}
